/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import { getPowerSdkInstance, IOperationResult } from '@pa-client/power-code-sdk/lib/';
import { dataSourcesInfo } from '../../.power/appschemas/dataSourcesInfo';
import { IGetOptions, IGetAllOptions } from '../Models/CommonModels';
import { ActivitesTransversales } from '../Models/ActivitesTransversalesModel';

export class ActivitesTransversalesService {
  private static readonly dataSourceName = 'activitestransversales';

  public static async create(record: Omit<ActivitesTransversales, 'ID'>): Promise<IOperationResult<ActivitesTransversales>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.createRecordAsync<Omit<ActivitesTransversales, 'ID'>, ActivitesTransversales>(
      ActivitesTransversalesService.dataSourceName,
      record
    );
    return result;
  }

  public static async update(id: string, changedFields: Partial<Omit<ActivitesTransversales, 'ID'>>): Promise<IOperationResult<ActivitesTransversales>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.updateRecordAsync<Partial<Omit<ActivitesTransversales, 'ID'>>, ActivitesTransversales>(
      ActivitesTransversalesService.dataSourceName,
      id.toString(),
      changedFields
    );
    return result;
  }

  public static async delete(id: string): Promise<void> {
    await getPowerSdkInstance(dataSourcesInfo).Data.deleteRecordAsync(ActivitesTransversalesService.dataSourceName, id.toString());
  }

  public static async get(id: string, options?: IGetOptions): Promise<IOperationResult<ActivitesTransversales>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveRecordAsync<ActivitesTransversales>(
      ActivitesTransversalesService.dataSourceName,
      id.toString(),
      options
    );
    return result;
  }

  public static async getAll(options?: IGetAllOptions): Promise<IOperationResult<ActivitesTransversales[]>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveMultipleRecordsAsync<ActivitesTransversales>(
      ActivitesTransversalesService.dataSourceName,
      options
    );
    return result;
  }
}
