/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import { getPowerSdkInstance, IOperationResult } from '@pa-client/power-code-sdk/lib/';
import { dataSourcesInfo } from '../../.power/appschemas/dataSourcesInfo';
import { IGetOptions, IGetAllOptions } from '../Models/CommonModels';
import { ActionRecouvrement } from '../Models/ActionRecouvrementModel';

export class ActionRecouvrementService {
  private static readonly dataSourceName = 'action recouvrement';

  public static async create(record: Omit<ActionRecouvrement, 'ID'>): Promise<IOperationResult<ActionRecouvrement>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.createRecordAsync<Omit<ActionRecouvrement, 'ID'>, ActionRecouvrement>(
      ActionRecouvrementService.dataSourceName,
      record
    );
    return result;
  }

  public static async update(id: string, changedFields: Partial<Omit<ActionRecouvrement, 'ID'>>): Promise<IOperationResult<ActionRecouvrement>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.updateRecordAsync<Partial<Omit<ActionRecouvrement, 'ID'>>, ActionRecouvrement>(
      ActionRecouvrementService.dataSourceName,
      id.toString(),
      changedFields
    );
    return result;
  }

  public static async delete(id: string): Promise<void> {
    await getPowerSdkInstance(dataSourcesInfo).Data.deleteRecordAsync(ActionRecouvrementService.dataSourceName, id.toString());
  }

  public static async get(id: string, options?: IGetOptions): Promise<IOperationResult<ActionRecouvrement>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveRecordAsync<ActionRecouvrement>(
      ActionRecouvrementService.dataSourceName,
      id.toString(),
      options
    );
    return result;
  }

  public static async getAll(options?: IGetAllOptions): Promise<IOperationResult<ActionRecouvrement[]>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveMultipleRecordsAsync<ActionRecouvrement>(
      ActionRecouvrementService.dataSourceName,
      options
    );
    return result;
  }
}
