/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import { getPowerSdkInstance, IOperationResult } from '@pa-client/power-code-sdk/lib/';
import { dataSourcesInfo } from '../../.power/appschemas/dataSourcesInfo';
import { IGetOptions, IGetAllOptions } from '../Models/CommonModels';
import { AgenceResau } from '../Models/AgenceResauModel';

export class AgenceResauService {
  private static readonly dataSourceName = 'agenceresau';

  public static async create(record: Omit<AgenceResau, 'ID'>): Promise<IOperationResult<AgenceResau>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.createRecordAsync<Omit<AgenceResau, 'ID'>, AgenceResau>(
      AgenceResauService.dataSourceName,
      record
    );
    return result;
  }

  public static async update(id: string, changedFields: Partial<Omit<AgenceResau, 'ID'>>): Promise<IOperationResult<AgenceResau>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.updateRecordAsync<Partial<Omit<AgenceResau, 'ID'>>, AgenceResau>(
      AgenceResauService.dataSourceName,
      id.toString(),
      changedFields
    );
    return result;
  }

  public static async delete(id: string): Promise<void> {
    await getPowerSdkInstance(dataSourcesInfo).Data.deleteRecordAsync(AgenceResauService.dataSourceName, id.toString());
  }

  public static async get(id: string, options?: IGetOptions): Promise<IOperationResult<AgenceResau>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveRecordAsync<AgenceResau>(
      AgenceResauService.dataSourceName,
      id.toString(),
      options
    );
    return result;
  }

  public static async getAll(options?: IGetAllOptions): Promise<IOperationResult<AgenceResau[]>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveMultipleRecordsAsync<AgenceResau>(
      AgenceResauService.dataSourceName,
      options
    );
    return result;
  }
}
