/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import { getPowerSdkInstance, IOperationResult } from '@pa-client/power-code-sdk/lib/';
import { dataSourcesInfo } from '../../.power/appschemas/dataSourcesInfo';
import { IGetOptions, IGetAllOptions } from '../Models/CommonModels';
import { AnalyseEngagements } from '../Models/AnalyseEngagementsModel';

export class AnalyseEngagementsService {
  private static readonly dataSourceName = 'analyseengagements';

  public static async create(record: Omit<AnalyseEngagements, 'ID'>): Promise<IOperationResult<AnalyseEngagements>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.createRecordAsync<Omit<AnalyseEngagements, 'ID'>, AnalyseEngagements>(
      AnalyseEngagementsService.dataSourceName,
      record
    );
    return result;
  }

  public static async update(id: string, changedFields: Partial<Omit<AnalyseEngagements, 'ID'>>): Promise<IOperationResult<AnalyseEngagements>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.updateRecordAsync<Partial<Omit<AnalyseEngagements, 'ID'>>, AnalyseEngagements>(
      AnalyseEngagementsService.dataSourceName,
      id.toString(),
      changedFields
    );
    return result;
  }

  public static async delete(id: string): Promise<void> {
    await getPowerSdkInstance(dataSourcesInfo).Data.deleteRecordAsync(AnalyseEngagementsService.dataSourceName, id.toString());
  }

  public static async get(id: string, options?: IGetOptions): Promise<IOperationResult<AnalyseEngagements>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveRecordAsync<AnalyseEngagements>(
      AnalyseEngagementsService.dataSourceName,
      id.toString(),
      options
    );
    return result;
  }

  public static async getAll(options?: IGetAllOptions): Promise<IOperationResult<AnalyseEngagements[]>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveMultipleRecordsAsync<AnalyseEngagements>(
      AnalyseEngagementsService.dataSourceName,
      options
    );
    return result;
  }
}
