/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import { getPowerSdkInstance, IOperationResult } from '@pa-client/power-code-sdk/lib/';
import { dataSourcesInfo } from '../../.power/appschemas/dataSourcesInfo';
import { IGetOptions, IGetAllOptions } from '../Models/CommonModels';
import { AnalyseDossiersComites } from '../Models/AnalyseDossiersComitesModel';

export class AnalyseDossiersComitesService {
  private static readonly dataSourceName = 'analysedossierscomites';

  public static async create(record: Omit<AnalyseDossiersComites, 'ID'>): Promise<IOperationResult<AnalyseDossiersComites>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.createRecordAsync<Omit<AnalyseDossiersComites, 'ID'>, AnalyseDossiersComites>(
      AnalyseDossiersComitesService.dataSourceName,
      record
    );
    return result;
  }

  public static async update(id: string, changedFields: Partial<Omit<AnalyseDossiersComites, 'ID'>>): Promise<IOperationResult<AnalyseDossiersComites>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.updateRecordAsync<Partial<Omit<AnalyseDossiersComites, 'ID'>>, AnalyseDossiersComites>(
      AnalyseDossiersComitesService.dataSourceName,
      id.toString(),
      changedFields
    );
    return result;
  }

  public static async delete(id: string): Promise<void> {
    await getPowerSdkInstance(dataSourcesInfo).Data.deleteRecordAsync(AnalyseDossiersComitesService.dataSourceName, id.toString());
  }

  public static async get(id: string, options?: IGetOptions): Promise<IOperationResult<AnalyseDossiersComites>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveRecordAsync<AnalyseDossiersComites>(
      AnalyseDossiersComitesService.dataSourceName,
      id.toString(),
      options
    );
    return result;
  }

  public static async getAll(options?: IGetAllOptions): Promise<IOperationResult<AnalyseDossiersComites[]>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveMultipleRecordsAsync<AnalyseDossiersComites>(
      AnalyseDossiersComitesService.dataSourceName,
      options
    );
    return result;
  }
}
