/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import { getPowerSdkInstance, IOperationResult } from '@pa-client/power-code-sdk/lib/';
import { dataSourcesInfo } from '../../.power/appschemas/dataSourcesInfo';
import { IGetOptions, IGetAllOptions } from '../Models/CommonModels';
import { AnalyseSuiviTransmission } from '../Models/AnalyseSuiviTransmissionModel';

export class AnalyseSuiviTransmissionService {
  private static readonly dataSourceName = 'analysesuivitransmission';

  public static async create(record: Omit<AnalyseSuiviTransmission, 'ID'>): Promise<IOperationResult<AnalyseSuiviTransmission>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.createRecordAsync<Omit<AnalyseSuiviTransmission, 'ID'>, AnalyseSuiviTransmission>(
      AnalyseSuiviTransmissionService.dataSourceName,
      record
    );
    return result;
  }

  public static async update(id: string, changedFields: Partial<Omit<AnalyseSuiviTransmission, 'ID'>>): Promise<IOperationResult<AnalyseSuiviTransmission>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.updateRecordAsync<Partial<Omit<AnalyseSuiviTransmission, 'ID'>>, AnalyseSuiviTransmission>(
      AnalyseSuiviTransmissionService.dataSourceName,
      id.toString(),
      changedFields
    );
    return result;
  }

  public static async delete(id: string): Promise<void> {
    await getPowerSdkInstance(dataSourcesInfo).Data.deleteRecordAsync(AnalyseSuiviTransmissionService.dataSourceName, id.toString());
  }

  public static async get(id: string, options?: IGetOptions): Promise<IOperationResult<AnalyseSuiviTransmission>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveRecordAsync<AnalyseSuiviTransmission>(
      AnalyseSuiviTransmissionService.dataSourceName,
      id.toString(),
      options
    );
    return result;
  }

  public static async getAll(options?: IGetAllOptions): Promise<IOperationResult<AnalyseSuiviTransmission[]>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveMultipleRecordsAsync<AnalyseSuiviTransmission>(
      AnalyseSuiviTransmissionService.dataSourceName,
      options
    );
    return result;
  }
}
