/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import { getPowerSdkInstance, IOperationResult } from '@pa-client/power-code-sdk/lib/';
import { dataSourcesInfo } from '../../.power/appschemas/dataSourcesInfo';
import { IGetOptions, IGetAllOptions } from '../Models/CommonModels';
import { AnalyseDelaisCredit } from '../Models/AnalyseDelaisCreditModel';

export class AnalyseDelaisCreditService {
  private static readonly dataSourceName = 'analysedelaiscredit';

  public static async create(record: Omit<AnalyseDelaisCredit, 'ID'>): Promise<IOperationResult<AnalyseDelaisCredit>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.createRecordAsync<Omit<AnalyseDelaisCredit, 'ID'>, AnalyseDelaisCredit>(
      AnalyseDelaisCreditService.dataSourceName,
      record
    );
    return result;
  }

  public static async update(id: string, changedFields: Partial<Omit<AnalyseDelaisCredit, 'ID'>>): Promise<IOperationResult<AnalyseDelaisCredit>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.updateRecordAsync<Partial<Omit<AnalyseDelaisCredit, 'ID'>>, AnalyseDelaisCredit>(
      AnalyseDelaisCreditService.dataSourceName,
      id.toString(),
      changedFields
    );
    return result;
  }

  public static async delete(id: string): Promise<void> {
    await getPowerSdkInstance(dataSourcesInfo).Data.deleteRecordAsync(AnalyseDelaisCreditService.dataSourceName, id.toString());
  }

  public static async get(id: string, options?: IGetOptions): Promise<IOperationResult<AnalyseDelaisCredit>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveRecordAsync<AnalyseDelaisCredit>(
      AnalyseDelaisCreditService.dataSourceName,
      id.toString(),
      options
    );
    return result;
  }

  public static async getAll(options?: IGetAllOptions): Promise<IOperationResult<AnalyseDelaisCredit[]>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveMultipleRecordsAsync<AnalyseDelaisCredit>(
      AnalyseDelaisCreditService.dataSourceName,
      options
    );
    return result;
  }
}
