/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import { getPowerSdkInstance, IOperationResult } from '@pa-client/power-code-sdk/lib/';
import { dataSourcesInfo } from '../../.power/appschemas/dataSourcesInfo';
import { IGetOptions, IGetAllOptions } from '../Models/CommonModels';
import { AnalyseSuiviMEP } from '../Models/AnalyseSuiviMEPModel';

export class AnalyseSuiviMEPService {
  private static readonly dataSourceName = 'analysesuivimep';

  public static async create(record: Omit<AnalyseSuiviMEP, 'ID'>): Promise<IOperationResult<AnalyseSuiviMEP>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.createRecordAsync<Omit<AnalyseSuiviMEP, 'ID'>, AnalyseSuiviMEP>(
      AnalyseSuiviMEPService.dataSourceName,
      record
    );
    return result;
  }

  public static async update(id: string, changedFields: Partial<Omit<AnalyseSuiviMEP, 'ID'>>): Promise<IOperationResult<AnalyseSuiviMEP>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.updateRecordAsync<Partial<Omit<AnalyseSuiviMEP, 'ID'>>, AnalyseSuiviMEP>(
      AnalyseSuiviMEPService.dataSourceName,
      id.toString(),
      changedFields
    );
    return result;
  }

  public static async delete(id: string): Promise<void> {
    await getPowerSdkInstance(dataSourcesInfo).Data.deleteRecordAsync(AnalyseSuiviMEPService.dataSourceName, id.toString());
  }

  public static async get(id: string, options?: IGetOptions): Promise<IOperationResult<AnalyseSuiviMEP>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveRecordAsync<AnalyseSuiviMEP>(
      AnalyseSuiviMEPService.dataSourceName,
      id.toString(),
      options
    );
    return result;
  }

  public static async getAll(options?: IGetAllOptions): Promise<IOperationResult<AnalyseSuiviMEP[]>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveMultipleRecordsAsync<AnalyseSuiviMEP>(
      AnalyseSuiviMEPService.dataSourceName,
      options
    );
    return result;
  }
}
