/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import { getPowerSdkInstance, IOperationResult } from '@pa-client/power-code-sdk/lib/';
import { dataSourcesInfo } from '../../.power/appschemas/dataSourcesInfo';
import { IGetOptions, IGetAllOptions } from '../Models/CommonModels';
import { ClientsenAnomalie } from '../Models/ClientsenAnomalieModel';

export class ClientsenAnomalieService {
  private static readonly dataSourceName = 'clients en anomalie';

  public static async create(record: Omit<ClientsenAnomalie, 'ID'>): Promise<IOperationResult<ClientsenAnomalie>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.createRecordAsync<Omit<ClientsenAnomalie, 'ID'>, ClientsenAnomalie>(
      ClientsenAnomalieService.dataSourceName,
      record
    );
    return result;
  }

  public static async update(id: string, changedFields: Partial<Omit<ClientsenAnomalie, 'ID'>>): Promise<IOperationResult<ClientsenAnomalie>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.updateRecordAsync<Partial<Omit<ClientsenAnomalie, 'ID'>>, ClientsenAnomalie>(
      ClientsenAnomalieService.dataSourceName,
      id.toString(),
      changedFields
    );
    return result;
  }

  public static async delete(id: string): Promise<void> {
    await getPowerSdkInstance(dataSourcesInfo).Data.deleteRecordAsync(ClientsenAnomalieService.dataSourceName, id.toString());
  }

  public static async get(id: string, options?: IGetOptions): Promise<IOperationResult<ClientsenAnomalie>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveRecordAsync<ClientsenAnomalie>(
      ClientsenAnomalieService.dataSourceName,
      id.toString(),
      options
    );
    return result;
  }

  public static async getAll(options?: IGetAllOptions): Promise<IOperationResult<ClientsenAnomalie[]>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveMultipleRecordsAsync<ClientsenAnomalie>(
      ClientsenAnomalieService.dataSourceName,
      options
    );
    return result;
  }
}
