/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import { getPowerSdkInstance, IOperationResult } from '@pa-client/power-code-sdk/lib/';
import { dataSourcesInfo } from '../../.power/appschemas/dataSourcesInfo';
import { IGetOptions, IGetAllOptions } from '../Models/CommonModels';
import { DetailsDossiers } from '../Models/DetailsDossiersModel';

export class DetailsDossiersService {
  private static readonly dataSourceName = 'detailsdossiers';

  public static async create(record: Omit<DetailsDossiers, 'ID'>): Promise<IOperationResult<DetailsDossiers>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.createRecordAsync<Omit<DetailsDossiers, 'ID'>, DetailsDossiers>(
      DetailsDossiersService.dataSourceName,
      record
    );
    return result;
  }

  public static async update(id: string, changedFields: Partial<Omit<DetailsDossiers, 'ID'>>): Promise<IOperationResult<DetailsDossiers>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.updateRecordAsync<Partial<Omit<DetailsDossiers, 'ID'>>, DetailsDossiers>(
      DetailsDossiersService.dataSourceName,
      id.toString(),
      changedFields
    );
    return result;
  }

  public static async delete(id: string): Promise<void> {
    await getPowerSdkInstance(dataSourcesInfo).Data.deleteRecordAsync(DetailsDossiersService.dataSourceName, id.toString());
  }

  public static async get(id: string, options?: IGetOptions): Promise<IOperationResult<DetailsDossiers>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveRecordAsync<DetailsDossiers>(
      DetailsDossiersService.dataSourceName,
      id.toString(),
      options
    );
    return result;
  }

  public static async getAll(options?: IGetAllOptions): Promise<IOperationResult<DetailsDossiers[]>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveMultipleRecordsAsync<DetailsDossiers>(
      DetailsDossiersService.dataSourceName,
      options
    );
    return result;
  }
}
