/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import { getPowerSdkInstance, IOperationResult } from '@pa-client/power-code-sdk/lib/';
import { dataSourcesInfo } from '../../.power/appschemas/dataSourcesInfo';
import { IGetOptions, IGetAllOptions } from '../Models/CommonModels';
import { DetailSurMepClient } from '../Models/DetailSurMepClientModel';

export class DetailSurMepClientService {
  private static readonly dataSourceName = 'detailsurmepclient';

  public static async create(record: Omit<DetailSurMepClient, 'ID'>): Promise<IOperationResult<DetailSurMepClient>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.createRecordAsync<Omit<DetailSurMepClient, 'ID'>, DetailSurMepClient>(
      DetailSurMepClientService.dataSourceName,
      record
    );
    return result;
  }

  public static async update(id: string, changedFields: Partial<Omit<DetailSurMepClient, 'ID'>>): Promise<IOperationResult<DetailSurMepClient>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.updateRecordAsync<Partial<Omit<DetailSurMepClient, 'ID'>>, DetailSurMepClient>(
      DetailSurMepClientService.dataSourceName,
      id.toString(),
      changedFields
    );
    return result;
  }

  public static async delete(id: string): Promise<void> {
    await getPowerSdkInstance(dataSourcesInfo).Data.deleteRecordAsync(DetailSurMepClientService.dataSourceName, id.toString());
  }

  public static async get(id: string, options?: IGetOptions): Promise<IOperationResult<DetailSurMepClient>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveRecordAsync<DetailSurMepClient>(
      DetailSurMepClientService.dataSourceName,
      id.toString(),
      options
    );
    return result;
  }

  public static async getAll(options?: IGetAllOptions): Promise<IOperationResult<DetailSurMepClient[]>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveMultipleRecordsAsync<DetailSurMepClient>(
      DetailSurMepClientService.dataSourceName,
      options
    );
    return result;
  }
}
