/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import { getPowerSdkInstance, IOperationResult } from '@pa-client/power-code-sdk/lib/';
import { dataSourcesInfo } from '../../.power/appschemas/dataSourcesInfo';
import { IGetOptions, IGetAllOptions } from '../Models/CommonModels';
import { FormationUnites } from '../Models/FormationUnitesModel';

export class FormationUnitesService {
  private static readonly dataSourceName = 'formationunites';

  public static async create(record: Omit<FormationUnites, 'ID'>): Promise<IOperationResult<FormationUnites>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.createRecordAsync<Omit<FormationUnites, 'ID'>, FormationUnites>(
      FormationUnitesService.dataSourceName,
      record
    );
    return result;
  }

  public static async update(id: string, changedFields: Partial<Omit<FormationUnites, 'ID'>>): Promise<IOperationResult<FormationUnites>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.updateRecordAsync<Partial<Omit<FormationUnites, 'ID'>>, FormationUnites>(
      FormationUnitesService.dataSourceName,
      id.toString(),
      changedFields
    );
    return result;
  }

  public static async delete(id: string): Promise<void> {
    await getPowerSdkInstance(dataSourcesInfo).Data.deleteRecordAsync(FormationUnitesService.dataSourceName, id.toString());
  }

  public static async get(id: string, options?: IGetOptions): Promise<IOperationResult<FormationUnites>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveRecordAsync<FormationUnites>(
      FormationUnitesService.dataSourceName,
      id.toString(),
      options
    );
    return result;
  }

  public static async getAll(options?: IGetAllOptions): Promise<IOperationResult<FormationUnites[]>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveMultipleRecordsAsync<FormationUnites>(
      FormationUnitesService.dataSourceName,
      options
    );
    return result;
  }
}
