/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import { getPowerSdkInstance, IOperationResult } from '@pa-client/power-code-sdk/lib/';
import { dataSourcesInfo } from '../../.power/appschemas/dataSourcesInfo';
import { IGetOptions, IGetAllOptions } from '../Models/CommonModels';
import { RechercherClientAnomalie } from '../Models/RechercherClientAnomalieModel';

export class RechercherClientAnomalieService {
  private static readonly dataSourceName = 'rechercherclientanomalie';

  public static async create(record: Omit<RechercherClientAnomalie, 'ID'>): Promise<IOperationResult<RechercherClientAnomalie>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.createRecordAsync<Omit<RechercherClientAnomalie, 'ID'>, RechercherClientAnomalie>(
      RechercherClientAnomalieService.dataSourceName,
      record
    );
    return result;
  }

  public static async update(id: string, changedFields: Partial<Omit<RechercherClientAnomalie, 'ID'>>): Promise<IOperationResult<RechercherClientAnomalie>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.updateRecordAsync<Partial<Omit<RechercherClientAnomalie, 'ID'>>, RechercherClientAnomalie>(
      RechercherClientAnomalieService.dataSourceName,
      id.toString(),
      changedFields
    );
    return result;
  }

  public static async delete(id: string): Promise<void> {
    await getPowerSdkInstance(dataSourcesInfo).Data.deleteRecordAsync(RechercherClientAnomalieService.dataSourceName, id.toString());
  }

  public static async get(id: string, options?: IGetOptions): Promise<IOperationResult<RechercherClientAnomalie>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveRecordAsync<RechercherClientAnomalie>(
      RechercherClientAnomalieService.dataSourceName,
      id.toString(),
      options
    );
    return result;
  }

  public static async getAll(options?: IGetAllOptions): Promise<IOperationResult<RechercherClientAnomalie[]>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveMultipleRecordsAsync<RechercherClientAnomalie>(
      RechercherClientAnomalieService.dataSourceName,
      options
    );
    return result;
  }
}
