/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import { getPowerSdkInstance, IOperationResult } from '@pa-client/power-code-sdk/lib/';
import { dataSourcesInfo } from '../../.power/appschemas/dataSourcesInfo';
import { IGetOptions, IGetAllOptions } from '../Models/CommonModels';
import { RepriseProvision } from '../Models/RepriseProvisionModel';

export class RepriseProvisionService {
  private static readonly dataSourceName = 'repriseprovision';

  public static async create(record: Omit<RepriseProvision, 'ID'>): Promise<IOperationResult<RepriseProvision>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.createRecordAsync<Omit<RepriseProvision, 'ID'>, RepriseProvision>(
      RepriseProvisionService.dataSourceName,
      record
    );
    return result;
  }

  public static async update(id: string, changedFields: Partial<Omit<RepriseProvision, 'ID'>>): Promise<IOperationResult<RepriseProvision>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.updateRecordAsync<Partial<Omit<RepriseProvision, 'ID'>>, RepriseProvision>(
      RepriseProvisionService.dataSourceName,
      id.toString(),
      changedFields
    );
    return result;
  }

  public static async delete(id: string): Promise<void> {
    await getPowerSdkInstance(dataSourcesInfo).Data.deleteRecordAsync(RepriseProvisionService.dataSourceName, id.toString());
  }

  public static async get(id: string, options?: IGetOptions): Promise<IOperationResult<RepriseProvision>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveRecordAsync<RepriseProvision>(
      RepriseProvisionService.dataSourceName,
      id.toString(),
      options
    );
    return result;
  }

  public static async getAll(options?: IGetAllOptions): Promise<IOperationResult<RepriseProvision[]>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveMultipleRecordsAsync<RepriseProvision>(
      RepriseProvisionService.dataSourceName,
      options
    );
    return result;
  }
}
