/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import { getPowerSdkInstance, IOperationResult } from '@pa-client/power-code-sdk/lib/';
import { dataSourcesInfo } from '../../.power/appschemas/dataSourcesInfo';
import { IGetOptions, IGetAllOptions } from '../Models/CommonModels';
import { SituationMEP } from '../Models/SituationMEPModel';

export class SituationMEPService {
  private static readonly dataSourceName = 'situationmep';

  public static async create(record: Omit<SituationMEP, 'ID'>): Promise<IOperationResult<SituationMEP>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.createRecordAsync<Omit<SituationMEP, 'ID'>, SituationMEP>(
      SituationMEPService.dataSourceName,
      record
    );
    return result;
  }

  public static async update(id: string, changedFields: Partial<Omit<SituationMEP, 'ID'>>): Promise<IOperationResult<SituationMEP>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.updateRecordAsync<Partial<Omit<SituationMEP, 'ID'>>, SituationMEP>(
      SituationMEPService.dataSourceName,
      id.toString(),
      changedFields
    );
    return result;
  }

  public static async delete(id: string): Promise<void> {
    await getPowerSdkInstance(dataSourcesInfo).Data.deleteRecordAsync(SituationMEPService.dataSourceName, id.toString());
  }

  public static async get(id: string, options?: IGetOptions): Promise<IOperationResult<SituationMEP>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveRecordAsync<SituationMEP>(
      SituationMEPService.dataSourceName,
      id.toString(),
      options
    );
    return result;
  }

  public static async getAll(options?: IGetAllOptions): Promise<IOperationResult<SituationMEP[]>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveMultipleRecordsAsync<SituationMEP>(
      SituationMEPService.dataSourceName,
      options
    );
    return result;
  }
}
