/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import { getPowerSdkInstance, IOperationResult } from '@pa-client/power-code-sdk/lib/';
import { dataSourcesInfo } from '../../.power/appschemas/dataSourcesInfo';
import { IGetOptions, IGetAllOptions } from '../Models/CommonModels';
import { SuiviDossiersRestructuration } from '../Models/SuiviDossiersRestructurationModel';

export class SuiviDossiersRestructurationService {
  private static readonly dataSourceName = 'suividossiersrestructuration';

  public static async create(record: Omit<SuiviDossiersRestructuration, 'ID'>): Promise<IOperationResult<SuiviDossiersRestructuration>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.createRecordAsync<Omit<SuiviDossiersRestructuration, 'ID'>, SuiviDossiersRestructuration>(
      SuiviDossiersRestructurationService.dataSourceName,
      record
    );
    return result;
  }

  public static async update(id: string, changedFields: Partial<Omit<SuiviDossiersRestructuration, 'ID'>>): Promise<IOperationResult<SuiviDossiersRestructuration>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.updateRecordAsync<Partial<Omit<SuiviDossiersRestructuration, 'ID'>>, SuiviDossiersRestructuration>(
      SuiviDossiersRestructurationService.dataSourceName,
      id.toString(),
      changedFields
    );
    return result;
  }

  public static async delete(id: string): Promise<void> {
    await getPowerSdkInstance(dataSourcesInfo).Data.deleteRecordAsync(SuiviDossiersRestructurationService.dataSourceName, id.toString());
  }

  public static async get(id: string, options?: IGetOptions): Promise<IOperationResult<SuiviDossiersRestructuration>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveRecordAsync<SuiviDossiersRestructuration>(
      SuiviDossiersRestructurationService.dataSourceName,
      id.toString(),
      options
    );
    return result;
  }

  public static async getAll(options?: IGetAllOptions): Promise<IOperationResult<SuiviDossiersRestructuration[]>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveMultipleRecordsAsync<SuiviDossiersRestructuration>(
      SuiviDossiersRestructurationService.dataSourceName,
      options
    );
    return result;
  }
}
