/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import { getPowerSdkInstance, IOperationResult } from '@pa-client/power-code-sdk/lib/';
import { dataSourcesInfo } from '../../.power/appschemas/dataSourcesInfo';
import { IGetOptions, IGetAllOptions } from '../Models/CommonModels';
import { SuiviDepassements } from '../Models/SuiviDepassementsModel';

export class SuiviDepassementsService {
  private static readonly dataSourceName = 'suividepassements';

  public static async create(record: Omit<SuiviDepassements, 'ID'>): Promise<IOperationResult<SuiviDepassements>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.createRecordAsync<Omit<SuiviDepassements, 'ID'>, SuiviDepassements>(
      SuiviDepassementsService.dataSourceName,
      record
    );
    return result;
  }

  public static async update(id: string, changedFields: Partial<Omit<SuiviDepassements, 'ID'>>): Promise<IOperationResult<SuiviDepassements>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.updateRecordAsync<Partial<Omit<SuiviDepassements, 'ID'>>, SuiviDepassements>(
      SuiviDepassementsService.dataSourceName,
      id.toString(),
      changedFields
    );
    return result;
  }

  public static async delete(id: string): Promise<void> {
    await getPowerSdkInstance(dataSourcesInfo).Data.deleteRecordAsync(SuiviDepassementsService.dataSourceName, id.toString());
  }

  public static async get(id: string, options?: IGetOptions): Promise<IOperationResult<SuiviDepassements>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveRecordAsync<SuiviDepassements>(
      SuiviDepassementsService.dataSourceName,
      id.toString(),
      options
    );
    return result;
  }

  public static async getAll(options?: IGetAllOptions): Promise<IOperationResult<SuiviDepassements[]>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveMultipleRecordsAsync<SuiviDepassements>(
      SuiviDepassementsService.dataSourceName,
      options
    );
    return result;
  }
}
