/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import { getPowerSdkInstance, IOperationResult } from '@pa-client/power-code-sdk/lib/';
import { dataSourcesInfo } from '../../.power/appschemas/dataSourcesInfo';
import { IGetOptions, IGetAllOptions } from '../Models/CommonModels';
import { SuiviAnomalies } from '../Models/SuiviAnomaliesModel';

export class SuiviAnomaliesService {
  private static readonly dataSourceName = 'suivianomalies';

  public static async create(record: Omit<SuiviAnomalies, 'ID'>): Promise<IOperationResult<SuiviAnomalies>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.createRecordAsync<Omit<SuiviAnomalies, 'ID'>, SuiviAnomalies>(
      SuiviAnomaliesService.dataSourceName,
      record
    );
    return result;
  }

  public static async update(id: string, changedFields: Partial<Omit<SuiviAnomalies, 'ID'>>): Promise<IOperationResult<SuiviAnomalies>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.updateRecordAsync<Partial<Omit<SuiviAnomalies, 'ID'>>, SuiviAnomalies>(
      SuiviAnomaliesService.dataSourceName,
      id.toString(),
      changedFields
    );
    return result;
  }

  public static async delete(id: string): Promise<void> {
    await getPowerSdkInstance(dataSourcesInfo).Data.deleteRecordAsync(SuiviAnomaliesService.dataSourceName, id.toString());
  }

  public static async get(id: string, options?: IGetOptions): Promise<IOperationResult<SuiviAnomalies>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveRecordAsync<SuiviAnomalies>(
      SuiviAnomaliesService.dataSourceName,
      id.toString(),
      options
    );
    return result;
  }

  public static async getAll(options?: IGetAllOptions): Promise<IOperationResult<SuiviAnomalies[]>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveMultipleRecordsAsync<SuiviAnomalies>(
      SuiviAnomaliesService.dataSourceName,
      options
    );
    return result;
  }
}
