/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import { getPowerSdkInstance, IOperationResult } from '@pa-client/power-code-sdk/lib/';
import { dataSourcesInfo } from '../../.power/appschemas/dataSourcesInfo';
import { IGetOptions, IGetAllOptions } from '../Models/CommonModels';
import { SuiviClientAppele } from '../Models/SuiviClientAppeleModel';

export class SuiviClientAppeleService {
  private static readonly dataSourceName = 'suiviclientappele';

  public static async create(record: Omit<SuiviClientAppele, 'ID'>): Promise<IOperationResult<SuiviClientAppele>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.createRecordAsync<Omit<SuiviClientAppele, 'ID'>, SuiviClientAppele>(
      SuiviClientAppeleService.dataSourceName,
      record
    );
    return result;
  }

  public static async update(id: string, changedFields: Partial<Omit<SuiviClientAppele, 'ID'>>): Promise<IOperationResult<SuiviClientAppele>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.updateRecordAsync<Partial<Omit<SuiviClientAppele, 'ID'>>, SuiviClientAppele>(
      SuiviClientAppeleService.dataSourceName,
      id.toString(),
      changedFields
    );
    return result;
  }

  public static async delete(id: string): Promise<void> {
    await getPowerSdkInstance(dataSourcesInfo).Data.deleteRecordAsync(SuiviClientAppeleService.dataSourceName, id.toString());
  }

  public static async get(id: string, options?: IGetOptions): Promise<IOperationResult<SuiviClientAppele>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveRecordAsync<SuiviClientAppele>(
      SuiviClientAppeleService.dataSourceName,
      id.toString(),
      options
    );
    return result;
  }

  public static async getAll(options?: IGetAllOptions): Promise<IOperationResult<SuiviClientAppele[]>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveMultipleRecordsAsync<SuiviClientAppele>(
      SuiviClientAppeleService.dataSourceName,
      options
    );
    return result;
  }
}
