/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import { getPowerSdkInstance, IOperationResult } from '@pa-client/power-code-sdk/lib/';
import { dataSourcesInfo } from '../../.power/appschemas/dataSourcesInfo';
import { IGetOptions, IGetAllOptions } from '../Models/CommonModels';
import { Utilisateurs } from '../Models/UtilisateursModel';

export class UtilisateursService {
  private static readonly dataSourceName = 'utilisateurs';

  public static async create(record: Omit<Utilisateurs, 'ID'>): Promise<IOperationResult<Utilisateurs>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.createRecordAsync<Omit<Utilisateurs, 'ID'>, Utilisateurs>(
      UtilisateursService.dataSourceName,
      record
    );
    return result;
  }

  public static async update(id: string, changedFields: Partial<Omit<Utilisateurs, 'ID'>>): Promise<IOperationResult<Utilisateurs>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.updateRecordAsync<Partial<Omit<Utilisateurs, 'ID'>>, Utilisateurs>(
      UtilisateursService.dataSourceName,
      id.toString(),
      changedFields
    );
    return result;
  }

  public static async delete(id: string): Promise<void> {
    await getPowerSdkInstance(dataSourcesInfo).Data.deleteRecordAsync(UtilisateursService.dataSourceName, id.toString());
  }

  public static async get(id: string, options?: IGetOptions): Promise<IOperationResult<Utilisateurs>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveRecordAsync<Utilisateurs>(
      UtilisateursService.dataSourceName,
      id.toString(),
      options
    );
    return result;
  }

  public static async getAll(options?: IGetAllOptions): Promise<IOperationResult<Utilisateurs[]>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveMultipleRecordsAsync<Utilisateurs>(
      UtilisateursService.dataSourceName,
      options
    );
    return result;
  }
}
