/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import { getPowerSdkInstance, IOperationResult } from '@pa-client/power-code-sdk/lib/';
import { dataSourcesInfo } from '../../.power/appschemas/dataSourcesInfo';
import { IGetOptions, IGetAllOptions } from '../Models/CommonModels';
import { VisiteClientele } from '../Models/VisiteClienteleModel';

export class VisiteClienteleService {
  private static readonly dataSourceName = 'visiteclientele';

  public static async create(record: Omit<VisiteClientele, 'ID'>): Promise<IOperationResult<VisiteClientele>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.createRecordAsync<Omit<VisiteClientele, 'ID'>, VisiteClientele>(
      VisiteClienteleService.dataSourceName,
      record
    );
    return result;
  }

  public static async update(id: string, changedFields: Partial<Omit<VisiteClientele, 'ID'>>): Promise<IOperationResult<VisiteClientele>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.updateRecordAsync<Partial<Omit<VisiteClientele, 'ID'>>, VisiteClientele>(
      VisiteClienteleService.dataSourceName,
      id.toString(),
      changedFields
    );
    return result;
  }

  public static async delete(id: string): Promise<void> {
    await getPowerSdkInstance(dataSourcesInfo).Data.deleteRecordAsync(VisiteClienteleService.dataSourceName, id.toString());
  }

  public static async get(id: string, options?: IGetOptions): Promise<IOperationResult<VisiteClientele>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveRecordAsync<VisiteClientele>(
      VisiteClienteleService.dataSourceName,
      id.toString(),
      options
    );
    return result;
  }

  public static async getAll(options?: IGetAllOptions): Promise<IOperationResult<VisiteClientele[]>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveMultipleRecordsAsync<VisiteClientele>(
      VisiteClienteleService.dataSourceName,
      options
    );
    return result;
  }
}
