/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import { getPowerSdkInstance, IOperationResult } from '@pa-client/power-code-sdk/lib/';
import { dataSourcesInfo } from '../../.power/appschemas/dataSourcesInfo';
import { IGetOptions, IGetAllOptions } from '../Models/CommonModels';
import { VolumeProvisions } from '../Models/VolumeProvisionsModel';

export class VolumeProvisionsService {
  private static readonly dataSourceName = 'volumeprovisions';

  public static async create(record: Omit<VolumeProvisions, 'ID'>): Promise<IOperationResult<VolumeProvisions>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.createRecordAsync<Omit<VolumeProvisions, 'ID'>, VolumeProvisions>(
      VolumeProvisionsService.dataSourceName,
      record
    );
    return result;
  }

  public static async update(id: string, changedFields: Partial<Omit<VolumeProvisions, 'ID'>>): Promise<IOperationResult<VolumeProvisions>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.updateRecordAsync<Partial<Omit<VolumeProvisions, 'ID'>>, VolumeProvisions>(
      VolumeProvisionsService.dataSourceName,
      id.toString(),
      changedFields
    );
    return result;
  }

  public static async delete(id: string): Promise<void> {
    await getPowerSdkInstance(dataSourcesInfo).Data.deleteRecordAsync(VolumeProvisionsService.dataSourceName, id.toString());
  }

  public static async get(id: string, options?: IGetOptions): Promise<IOperationResult<VolumeProvisions>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveRecordAsync<VolumeProvisions>(
      VolumeProvisionsService.dataSourceName,
      id.toString(),
      options
    );
    return result;
  }

  public static async getAll(options?: IGetAllOptions): Promise<IOperationResult<VolumeProvisions[]>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveMultipleRecordsAsync<VolumeProvisions>(
      VolumeProvisionsService.dataSourceName,
      options
    );
    return result;
  }
}
