/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

export interface ActionRecouvrement {
  ID?: number;
  Title?: string;
  "Statut#Id"?: number;
  Statut?: Record<string, unknown>;
  "Typedaction#Id"?: number;
  Typedaction?: Record<string, unknown>;
  DatePlanification?: string;
  DateExc_x00e9_cution?: string;
  Matricule?: string;
  Created?: string;
  "Author#Claims"?: string;
  Author?: Record<string, unknown>;
  DateprochaineAction?: string;
  NomClient?: string;
  NombreActionPlaniif_x00e9_?: number;
  Origineimpay_x00e9_?: string;
  "Collegueayantprispart#Claims"?: string;
  Collegueayantprispart?: Record<string, unknown>;
  Lienpi_x00e8_cejointe?: string;
  Modified?: string;
  EmailGFC?: string;
  OData__ColorTag?: string;
  ComplianceAssetId?: string;
  "Editor#Claims"?: string;
  Editor?: Record<string, unknown>;
  "{Identifier}"?: string;
  "{IsFolder}"?: boolean;
  "{Thumbnail}"?: Record<string, unknown>;
  "{Link}"?: string;
  "{Name}"?: string;
  "{FilenameWithExtension}"?: string;
  "{Path}"?: string;
  "{FullPath}"?: string;
  "{ModerationStatus}"?: string;
  "{ModerationComment}"?: string;
  "{ContentType}#Id"?: string;
  "{ContentType}"?: Record<string, unknown>;
  "{HasAttachments}"?: boolean;
  "{Attachments}@odata.type"?: string;
  "{Attachments}"?: unknown;
  "{VersionNumber}"?: string;
  "{TriggerWindowStartToken}"?: string;
  "{TriggerWindowEndToken}"?: string;
}
