/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

export interface DetailsDossiers {
  ID?: number;
  Title?: string;
  NomClient?: string;
  Matricule?: string;
  MontantSollicite?: number;
  Decision?: string;
  DetailDecision?: string;
  ObjetCommentaire?: string;
  Commentaire?: string;
  Comite?: string;
  "Author#Claims"?: string;
  Author?: Record<string, unknown>;
  Created?: string;
  Reference?: string;
  Date?: string;
  OData__ColorTag?: string;
  ComplianceAssetId?: string;
  Modified?: string;
  "Editor#Claims"?: string;
  Editor?: Record<string, unknown>;
  "{Identifier}"?: string;
  "{IsFolder}"?: boolean;
  "{Thumbnail}"?: Record<string, unknown>;
  "{Link}"?: string;
  "{Name}"?: string;
  "{FilenameWithExtension}"?: string;
  "{Path}"?: string;
  "{FullPath}"?: string;
  "{ModerationStatus}"?: string;
  "{ModerationComment}"?: string;
  "{ContentType}#Id"?: string;
  "{ContentType}"?: Record<string, unknown>;
  "{HasAttachments}"?: boolean;
  "{Attachments}@odata.type"?: string;
  "{Attachments}"?: unknown;
  "{VersionNumber}"?: string;
  "{TriggerWindowStartToken}"?: string;
  "{TriggerWindowEndToken}"?: string;
}
